contact_links:
  - name: Community Support and Questions
    url: https://github.com/localzet/aura/discussions
    about: Please ask and answer questions there. The issue tracker is for issues with core.
